// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDa5Jqt4mNHOa7sawTZisHU0MVVtgfTE8',
    appId: '1:159202080738:web:0b9e6b379e32025883ebbb',
    messagingSenderId: '159202080738',
    projectId: 'brainova-test',
    authDomain: 'brainova-test.firebaseapp.com',
    storageBucket: 'brainova-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGObbfoBuecSD1VIlQil4g0BJvvUI0Ays',
    appId: '1:159202080738:android:7709d292a4b0815b83ebbb',
    messagingSenderId: '159202080738',
    projectId: 'brainova-test',
    storageBucket: 'brainova-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDa5Jqt4mNHOa7sawTZisHU0MVVtgfTE8',
    appId: '1:159202080738:web:1f126a5eaa83dd4b83ebbb',
    messagingSenderId: '159202080738',
    projectId: 'brainova-test',
    authDomain: 'brainova-test.firebaseapp.com',
    storageBucket: 'brainova-test.firebasestorage.app',
  );
}
