name: brainova
description: "App d'étude collaborative - Brillez ensemble !"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Firebase (pour auth et base de données)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Firestore ODM (comme le prof)
  firestore_odm: ^3.0.2
  json_annotation: ^4.9.0

  # State management
  provider: ^6.1.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Pour générer le code ODM
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  dto:
    path: ../dto

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # Fonts (optionnel - Montserrat ou autre)
  # fonts:
  #   - family: SpaceGrotesk
  #     fonts:
  #       - asset: assets/fonts/SpaceGrotesk-Regular.ttf
  #       - asset: assets/fonts/SpaceGrotesk-Bold.ttf
  #         weight: 700